name: PaRappa the Rapper (Sep 24, 1996 prototype)
sha1: 535bc6a3b588b496aa9ffd83d8e8dc832f546b54
options:
  basename: prr.bin
  target_path: disc/PRR.BIN
  elf_path: build/prr.bin.elf
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/prr.bin
  src_path: src/prr.bin
  build_path: build
  # create_asm_dependencies: True

  ld_script_path: linker/prr.bin.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x80082388
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path: config/symbol_addrs.prr.bin.txt
  reloc_addrs_path: config/reloc_addrs.prr.bin.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.prr.bin.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.prr.bin.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False
segments:
  - name: header
    type: headerproto
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    bss_size: 0x149B60
    align: 4
    subsegments:
      - [0x800, .rodata, address]
      - [0x804, .rodata, prcard]
      - [0x9F8, .rodata, prcmenu_1]
      - [0xBBC, .rodata, prcd]
      - [0xD20, .rodata, prcompo]
      - [0xE50, .rodata, prcompo_1]
      # - [0xE7C, .rodata, prmenu]
      - [0xE7C, rodata, E7C]
      - [0xFCC, .rodata, prrap]
      - [0xFF4, .rodata, prstrm]
      - [0x1090, .rodata, prvdatal]
      - [0x14D8, rodata, 14D8]
      # - [0x14D8, .rodata, prvdbg]
      - [0x17C0, .rodata, prmime]
      - [0x17E8, rodata, 17E8] # psy-q

      - [0x279C, c, praction] 
      - [0x3D28, c, praction_1]
      - [0x7120, c, prapp]
      - [0x86F0, c, prcard]
      - [0x9ADC, c, prcmenu]
      - [0xAD14, c, prcmenu_1]
      - [0xDC90, c, prcd]
      - [0xF714, c, prcompo]
      - [0x20004, c, prcompo_1]
      - [0x21514, c, prevent]
      - [0x227AC, c, prevent_1]
      - [0x231A4, c, prmain]
      - [0x231F0, c, prmemory]
      - [0x238A8, c, prmenu]
      - [0x25AF8, c, prrap]
      - [0x261D4, c, prstrm]
      - [0x26AE4, c, prstrm_1]
      - [0x26C38, c, prpract]
      - [0x27ABC, c, prvdbg]
      - [0x28F18, c, prmime]
      - [0x2A02C, asm, 2A02C] # psy-q

      - [0x52D38, .data, praction]
      - [0x52D68, data, prapp]
      - [0x52E3C, .data, prcard]
      - [0x52E6C, .data, prcmenu]
      - [0x5319C, .data, prcd]
      - [0x53200, .data, prcompo]
      - [0x53230, .data, prcompo_data]
      - [0x580D4, .data, prevent]
      - [0x58128, data, prmain]
      - [0x58158, .data, prmemory]
      - [0x58188, data, prmenu]
      - [0x584FC, .data, prrap]
      - [0x58538, .data, prstrm]
      - [0x585B0, .data, prvdatal]
      - [0x59278, data, prpract]
      - [0x593AC, .data, prvtext]
      - [0x593DC, .data, prvdbg]
      - [0x595E8, data, 595E8] # psy-q

      - [0x72B88, .sdata, praction]
      - [0x72B9C, .sdata, praction_1]
      - [0x72BA8, .sdata, prcard]
      - [0x72BB0, .sdata, prcmenu_1]
      - [0x72BE0, .sdata, prcd]
      - [0x72BE8, .sdata, prcompo]
      - [0x72C88, .sdata, prcompo_1]
      - [0x72C8C, .sdata, prmemory]
      - [0x72C94, sdata, 72C94]
      - [0x72D30, .sdata, prrap]
      - [0x72D4C, .sdata, prstrm]
      - [0x72D50, .sdata, prstrm_1]
      - [0x72D54, .sdata, prvdatal]
      - [0x72DC0, sdata, 72DC0]
      - [0x72EB0, .sdata, prmime]

      - [0x72EBC, pad]

      - { vram: 0x800826BC, type: .sbss, name: praction }
      - { vram: 0x800826D4, type: .sbss, name: praction_1 }
      - { vram: 0x800826D8, type: sbss, name: prapp }
      - { vram: 0x800826DC, type: .sbss, name: prcard_1 }
      - { vram: 0x80082708, type: .sbss, name: prcmenu_1 }
      - { vram: 0x80082734, type: .sbss, name: prcd_1 }
      - { vram: 0x80082748, type: .sbss, name: prcompo_1 }
      - { vram: 0x80082784, type: sbss, name: prevent }
      - { vram: 0x800827A8, type: .sbss, name: prstrm_1 }
      - { vram: 0x800827BC, type: sbss }
      - { vram: 0x800827D4, type: bss }
  - [0x73000]
