name: Scene 6 Comod
sha1: 2036c482960fa77ecffb49d2f2959b15f1fd00fb
options:
  basename: scene6
  target_path: disc/S6/COMOD6.BIN
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/scene6
  src_path: src/scene6
  build_path: build/

  ld_script_path: linker/scene6.ld

  find_file_boundaries: False
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.scene6.txt
    - config/symbol_addrs.prr.bin.txt
  reloc_addrs_path:
    - configs/reloc_addrs.scene6.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.scene6.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.scene6.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  ld_bss_is_noload: False
segments:
  - name: scene6
    type: code
    start: 0x0
    vram: 0x801CC21C
    bss_size: 0x20000 # TODO: More proper size here
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, 0] # prsqevs6
      - [0x7DC, rodata, 7DC] # prscn6
      
      - [0x814, c, prscn6]
      - [0xB6A0, data, prscn6]
      - [0xB6E8, data, prsqevs6]
      - { vram: 0x801E3A5C, type: bss }
  - [0x24640]
