name: Scene 9 Comod
sha1: 877e81ed0ba64d1ac53ed2ef5d4f0d3c9260a377
options:
  basename: scene9
  target_path: disc/S9/COMOD9.BIN
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/scene9
  src_path: src/scene9
  build_path: build/

  ld_script_path: linker/scene9.ld

  find_file_boundaries: False
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.scene9.txt
    - config/symbol_addrs.prr.bin.txt
  reloc_addrs_path:
    - configs/reloc_addrs.scene9.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.scene9.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.scene9.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  ld_bss_is_noload: False
segments:
  - name: scene9
    type: code
    start: 0x0
    vram: 0x801CC21C
    bss_size: 0x20000 # TODO: More proper size here
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, 0] # prscn9
      
      - [0x20, c, prscn9]
      - [0x5CEC, data, prscn9]
      - [0x5D34, data, prsqevs9]
      - { vram: 0x801D26EC, type: bss }
  - [0xD7A8]
